spring.application.name=movieProject


# H2 ??
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Datasource ??
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=

#Spring Security Settings
logging.level.org.springframework.security.web=trace

spotify.client-id=2c7a7f34f3f8af01dcdae0baf5402da0
spotify.client-secret=a54fe02c00d49517cb43b138b5197ce8